import Head from "next/head";
import React from "react";
import { useEffect } from "react";
import { useState } from "react";
import Banner3 from "../components/banner/Banner3";
import Home3Blog from "../components/blog/Home3Blog";
import Category from "../components/category/Category";
import CounterUp from "../components/common/CounterUp";
import Header from "../components/common/Header";
import Preloader from "../components/common/Preloader";
import Footer3 from "../components/footer/Footer3";
import LiveAuction3 from "../components/LiveAution/LiveAuction3";
import SponsorHome1 from "../components/soponsor/Sponsor";
import Testimonial3 from "../components/testimonial/Testimonial3";
import UpCommingLiveAuction3 from "../components/upCommingLiveAuction/UpCommingLiveAuction3";

function Home3() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    if (typeof window !== "undefined") {
      setLoading(false);
    }
    setTimeout(() => {
      setLoading(true);
    }, 3000);
  }, []);
  return (
    <>
      {!loading ? (
        <Preloader classText="preloader style-3" />
      ) : (
        <>
          <Head>
            <title>Bidout - Multivendor Bid and Auction Next Js Template</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="assets/images/bg/sm-logo3.png" />
          </Head>
          <Header logo="header3-logo" />
          <Banner3 />
          <Category classTest="style2" />
          <LiveAuction3 />
          <Testimonial3 />
          <UpCommingLiveAuction3 />
          <SponsorHome1 classText="style-3" />
          <Home3Blog />
          <CounterUp />
          <Footer3 />
        </>
      )}
    </>
  );
}

export default Home3;
