import Head from "next/head";
import { useEffect } from "react";
import { useState } from "react";
import Banner1 from "../components/banner/Banner1";
import Home1Blog from "../components/blog/Home1Blog";
import Category from "../components/category/Category";
import CounterUp from "../components/common/CounterUp";
import Footer from "../components/common/Footer";
import Header from "../components/common/Header";
import Preloader from "../components/common/Preloader";
import Topbar from "../components/common/Topbar";
import LiveAution1 from "../components/LiveAution/LiveAution1";
import SponsorHome1 from "../components/soponsor/Sponsor";
import Testimonial1 from "../components/testimonial/Testimonial1";
import UpCommingLiveAuction1 from "../components/upCommingLiveAuction/UpCommingLiveAuction1";

function Home() {
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(false);
    setTimeout(() => {
      setLoading(true);
    }, 1000);
  }, []);
  return (
    <>
      {!loading ? (
        <Preloader classText="preloader" />
      ) : (
        <>
          <Head>
            <title>Bidout - Multivendor Bid and Auction Next JS Template</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="assets/images/bg/sm-logo.png" />
          </Head>
          <Topbar />
          <Header logo={"header-logo"} />
          <Banner1 />
          <Category />
          <LiveAution1 />
          <UpCommingLiveAuction1 />
          <Testimonial1 />
          <SponsorHome1 classText="style-1" />
          <Home1Blog />
          <CounterUp />
          <Footer />
        </>
      )}
    </>
  );
}
export default Home;
