import Head from "next/head";
import React from "react";

function Preloader({ classText }) {
  return (
    <>
      <Head>
        <title>Loading....</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={classText}>
        <div className="loader">
          <span></span>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
    </>
  );
}

export default Preloader;
